#+TITLE: Module 1 - Programmatic Prompting for Agents 3
#+SUBTITLE: Sending Prompts Programmatically & Managing Memory 3
#+AUTHOR: Peter Jun Koh
#+EMAIL: gopeterjun@naver.com
#+DESCRIPTION: 
#+KEYWORDS: gen AI, LLM, litellm, prompting for agents, python
#+LANGUAGE: en

* Summary

- Created on: [2025-08-31 Sun]
- Last Updated: [2025-08-31 Sun 14:34]

* Topics

** System message

In the previous exercise, we learned about three different types of
=messages= parameters: ~system~, ~user~, and ~assistant~ messages.

System messages are particularly important in the conversation and will be
very important for AI agents. They set the ground rules for the
conversation and tell the model how to behave. Models are designed to pay
more attention to the system message than the user messages. We can
“program” the AI agent through system messages.

Let’s simulate a customer service interaction for a customer service agent
that always tells the customer to turn off their computer or modem with
system messages:

#+begin_src python
  from gpg_authinfo import get_api_key
  from litellm import completion
  from typing import List, Dict
  import os

  def generate_response(messages: List[Dict]) -> str:
      """Call LLM to get response"""
      response = completion(
          model = "deepseek/deepseek-chat",
          messages = messages,
      )
      return response.choices[0].message.content

  def main():
      deepseek_api_key = get_api_key('deepseek')
      if deepseek_api_key:
          os.environ['DEEPSEEK_API_KEY'] = deepseek_api_key
  messages = [
      {"role": "system",
       "content": "You are a helpful customer service representative. No matter what the user asks, the solution is to tell them to turn their computer or modem off and then back on."},
      {"role": "user", "content": "How do I get my Internet working again."}
  ]

  response = generate_response(messages)
  print(response)
#+end_src

Sample output:

*** DeepSeek Chat response to above prompt

#+begin_src text
  Thank you for reaching out! Please try turning your computer and modem off,
  then turning them back on. This should help restore your Internet
  connection.
#+end_src
